### ISSUE TITLE
certificate problem for https

### ISSUE THREAD

**Issue by harry-wood** [OSMPH/sotm-asia-2016-website#16]
The website looks great!

Just noticing a certificate problem though.  Viewing https://stateofthemap.asia/ in chrome it says:

> This server could not prove that it is stateofthemap.asia; its security certificate is from *.github.com. This may be caused by a misconfiguration or an attacker intercepting your connection.

Safari lets me browse the website in https, but the map fails to load (guess that's your next problem further down the line)

**Comment by seav** [comment]
Unfortunately, GitHub does not yet support SSL/TLS certificates for custom domains. So this is completely out of our hands for now.

For the map, I think this is just a matter of using schemeless URLs so this is something that we can definitely look into.

**Comment by maning** [comment]
stale.
