### ISSUE TITLE
Call for Presenters

### ISSUE THREAD

**Issue by govvin** [OSMPH/sotm-asia-2016-website#4]
A few ideas to help you get started:
# Call for Presenters
## Resiliency
- OSM and Disaster Risk Management
## OSM in Government
- Mapping Agencies using Volunteered Geographic Information
- National Government Agencies using VGI
- Provincial Governments using VGI
- Municipal Government Units using VGI
- Barrangay Government Units using VGI
## The State of the Map Asia
- PH
- JP
- BA
- KH
- TW
- ID
- IN
- VN
- TH
## Cartography and Design
- Processing  OSM Data
- Benefits of Data Imports to OSM: OSMapaaralan
## OSM Mapping Niches
- Indoor Maps in OSM 
- Camera Mapping with Data Loggers
- Local  Outreach, Local Communities

**Comment by maning** [comment]
moved to trello
